### ISSUE TITLE
WaitStrategy::LogMatch not possible because StdIoKind is private member

### ISSUE THREAD

**Issue by dvzrv** [wefoxplatform/rustainers#20]
Hi! :wave: 

I've been looking into using this crate in CI and wanted to use `WaitStrategy::LogMatch`.
This was unfortunately not possible because [`StdIoKind` is used privately](https://github.com/wefoxplatform/rustainers/blob/c5b9c2413702accf45627d8893d4ee0d90a7c4f4/rustainers/src/container/wait_condition.rs#L4).

**Comment by davidB** [comment]
Hi,

the following factory functions don't match your need?

- `WaitStrategy::stdout_contains(s: impl Into<String>)`
- `WaitStrategy::stderr_contains(s: impl Into<String>)`
- `WaitStrategy::stdout_match(re: regex::Regex)` (feature = "regex")
- `WaitStrategy::stderr_match(re: regex::Regex)` (feature = "regex")

**Comment by dvzrv** [comment]
Ah, I wasn't aware of those! (It could be very useful to add those to examples).

Either way, I am not able to use e.g. `stdout_contains()`. It seems to never match the output and the test never returns.
I'll try Regex now, but I don't think that will yield much different results if contains doesn't work.

Just for a reality check: Do these contains/match functions check the output of what one would see e.g. when running `podman run --rm -ti <image>`?

**Comment by dvzrv** [comment]
The only thing that helped in my case was to add a sleep for the thread after starting the container... :sob: 

I'm a bit puzzled as to what else to try.

From the output of
```
podman run --rm -ti --network=pasta:-t,auto,-u,auto,-T,auto,-U,auto docker.io/nitrokey/nethsm:testing
[..]
2024-04-01 17:05:11 +00:00: INF [keyfender] listening on 8443/TCP for HTTPS
```

I'm trying to use `stdout_contains()` for `listening on 8443/TCP for HTTPS`, but the test never returns.
Is there maybe something else I should be aware of?

**Comment by davidB** [comment]
You have a sample of stdout_contains in the Mongo images at https://github.com/wefoxplatform/rustainers/blob/c5b9c2413702accf45627d8893d4ee0d90a7c4f4/rustainers/src/images/mongo.rs#L81

Can you share your failing rust code?

**Comment by IgorLaborieWefox** [comment]
You may prefer using the `WaitStrategy::https("path/to/something/return/ok")` in your case.
See https://docs.rs/rustainers/latest/rustainers/enum.WaitStrategy.html#method.https

**Comment by dvzrv** [comment]
> You have a sample of stdout_contains in the Mongo images at

Thanks, I have tried that, but it doesn't work (blocks forever).

> Can you share your failing rust code?

It's unfortunately only local atm. but here is a minimum reproducer:

```toml
[package]
name = "rustainers-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustainers = "0.12.0"
testresult = "0.4.0"
tokio = { version = "1.37.0", features = ["macros"] }
```

```rust
// SPDX-FileCopyrightText: 2024 David Runge <dvzrv@archlinux.org>
// SPDX-License-Identifier: Apache-2.0 OR MIT

use rustainers::{
    runner::Runner, ExposedPort, ImageName, Port, RunnableContainer, RunnableContainerBuilder,
    ToRunnableContainer, WaitStrategy,
};
use std::time::Duration;
use testresult::TestResult;
use tokio::time::sleep;

static IMAGE_NAME: &ImageName = &ImageName::new("docker.io/nitrokey/nethsm:testing");
static DEFAULT_PORT: u16 = 8443;
static DEFAULT_PATH: &str = "/api/v1";

#[derive(Debug)]
pub struct NetHsmImage {
    pub image: ImageName,
    pub port: ExposedPort,
}

impl NetHsmImage {
    pub async fn url(&self) -> TestResult<String> {
        Ok(format!(
            "https://localhost:{}{}",
            self.port.host_port().await?,
            DEFAULT_PATH
        ))
    }
}

impl Default for NetHsmImage {
    fn default() -> Self {
        Self {
            image: IMAGE_NAME.clone(),
            port: ExposedPort::new(DEFAULT_PORT),
        }
    }
}

impl ToRunnableContainer for NetHsmImage {
    fn to_runnable(&self, builder: RunnableContainerBuilder) -> RunnableContainer {
        builder
            .with_image(self.image.clone())
            // NOTE: this works directly, but follow-up tests are then started too fast, leading to TLS errors
            // .with_wait_strategy(WaitStrategy::ScanPort {
            //     container_port: Port::new(8443),
            //     timeout: Duration::from_secs(2),
            // })
            // NOTE: This blocks forever
            .with_wait_strategy(WaitStrategy::HttpSuccess {
                https: false,
                path: "api/v1/info".to_string(),
                container_port: Port::new(8080),
            })
            // NOTE: This blocks forever
            // .with_wait_strategy(WaitStrategy::stdout_contains(
            //     "listening on 8443/TCP for HTTPS",
            // ))
            .with_port_mappings([self.port.clone()])
            .build()
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() -> TestResult {
    let runner = Runner::podman()?;
    let image = NetHsmImage::default();
    println!("image: {:#?}", image.image);

    println!("Starting container...");
    let container = runner.start(image).await?;

    println!("serving URL: {}", container.url().await?);

    // NOTE: this works, but is of course brittle, depending on how fast the host is
    sleep(Duration::from_millis(2000)).await;
    println!("slept for 2s");

    Ok(())
}
```

> You may prefer using the WaitStrategy::https("path/to/something/return/ok") in your case.

I tried that as well, but it also blocks forever.

When trying with https on 8443:
```
2024-04-01 17:59:14 +00:00: INF [keyfender] listening on 8080/TCP for HTTP
2024-04-01 17:59:14 +00:00: INF [keyfender] listening on 8443/TCP for HTTPS
2024-04-01 17:59:14 +00:00: INF [conduit_mirage] listen: (Fatal InvalidMessage)
2024-04-01 17:59:14 -00:00: INF [conduit_mirage] [1] listen: (Fatal InvalidMessage)
2024-04-01 17:59:14 -00:00: INF [conduit_mirage] [2] listen: (Fatal InvalidMessage)
[..]
```

When trying without https on 8080:

```
2024-04-01 18:01:09 +00:00: INF [keyfender] listening on 8080/TCP for HTTP
2024-04-01 18:01:09 +00:00: INF [keyfender] listening on 8443/TCP for HTTPS
```

To my knowledge the container images are created from these files: https://github.com/Nitrokey/nethsm/tree/main/src/container/alpine

Maybe I'm doing something wrong? I've tried a lot of things now, but only manually waiting after creation seems to work.

**Comment by IgorLaborieWefox** [comment]
The

```
2024-04-01 18:01:09 +00:00: INF [keyfender] listening on 8080/TCP for HTTP
2024-04-01 18:01:09 +00:00: INF [keyfender] listening on 8443/TCP for HTTPS
```
 are on `stderr`.

Use

```rust
 .with_wait_strategy(WaitStrategy::stderr_contains(
     "listening on 8443/TCP for HTTPS",
 ))
```

**Comment by dvzrv** [comment]
Thanks again for being so patient and helping me debug this!

It helped me remove the custom wait logic and cut down on a lot of code! :partying_face: 

Thanks for this really useful crate!
