### ISSUE TITLE
Is there a way to specify how long to wait for the stdout contains text?

### ISSUE THREAD

**Issue by sergeda** [wefoxplatform/rustainers#22]
I'm trying to run docker compose file with two containers: one for the Postgres db and another one for the Liquibase migration tool. I'm trying to wait until migrations applied with:
```.with_wait_strategies([
                ("liquibase", WaitStrategy::stdout_contains("Liquibase command 'update' was executed successfully"))])
```
When starting docker-compose file manually db is getting created and then migration applies printing to console:

> liquibase-1  | Liquibase: Update has been successful.
> liquibase-1  | Liquibase command 'update' was executed successfully.
> liquibase-1 exited with code 0

So I thought my strategy should work but unfortunately it doesn't.
I think maybe that's because of the timeout, but can't find the way to specify timeout for the strategy.

Here is the error I'm getting:

> ContainerError(WaitConditionUnreachable(ContainerId("f45fedc4e84d0f92a5d7321974094173c75f509a3c205b6fd285bcd6867b251b"), LogMatch { io: Out, matcher: Contains("Liquibase command 'update' was executed successfully") }))

Any suggestions how to do this correctly?

**Comment by IgorLaborieWefox** [comment]
Have you tried `stderr` instead of `stdout`?

**Comment by IgorLaborieWefox** [comment]
And no, there is no timeout with the wait strategy.

You can do that in your test with https://docs.rs/tokio/1.37.0/tokio/time/fn.timeout.html

**Comment by sergeda** [comment]
> `stderr`

Switching to `stderr` helped. Thanks a lot
