### ISSUE TITLE
How to get ip and port from the Container with GenericImage?

### ISSUE THREAD

**Issue by sergeda** [wefoxplatform/rustainers#30]
I'm trying to run image like this:
```
    let mut nats = GenericImage::new("nats:latest".parse::<ImageName>().unwrap());
    nats.set_wait_strategy(WaitStrategy::stdout_contains("Listening for client connections")); 
    nats.add_port_mapping(4222);

    let runner = Runner::auto().unwrap();
    let container: Container<GenericImage> = runner.start(nats).await.unwrap();

```
But how can I get ip of the container from this point?

**Comment by ilaborie** [comment]
With the current code, you cannot easily get the IP of the container with the `GenericContainer`.

The current workaround is create a `Nats` image, there are examples in the code like <https://github.com/wefoxplatform/rustainers/blob/main/rustainers/src/images/redis.rs>

Ideally, we should add 

```rust
impl Container<GenericImage> {
  pub fn host_port(container_port: impl Into<Port>) -> Result<Port, PortError> {
    todo!()
  } 
}
```

If you are interested, you can contribute?

**Comment by sergeda** [comment]
Thank you. Created [PR](https://github.com/wefoxplatform/rustainers/pull/31) with NATS image
